# Generated by Django 3.2.21 on 2023-10-29 15:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('warehouse', '0002_auto_20231027_1902'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialReceiptSheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=200, verbose_name='MRS Number')),
                ('vendor', models.CharField(max_length=100, verbose_name='Vendor')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mrs', to='core.user', verbose_name='ثبت شده توسط')),
                ('pl', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mrs', to='warehouse.packinglist', verbose_name='Packing List Number')),
                ('po', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mrs', to='warehouse.procurementorder', verbose_name='PO Number')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mrs', to='warehouse.project', verbose_name='Project')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mrs', to='warehouse.warehouse', verbose_name='Warehouse')),
            ],
            options={
                'verbose_name': 'Material Receipt Sheet',
                'verbose_name_plural': 'Material Receipt Sheets',
                'ordering': ['-created'],
            },
        ),
    ]
