# Generated by Django 3.2.21 on 2023-10-29 15:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0004_inventoryitem_mrsitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryitem',
            name='cluster',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ivitems', to='warehouse.cluster', verbose_name='cluster'),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='pipeline',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ivitems', to='warehouse.pipeline', verbose_name='pipe line'),
        ),
    ]
