# Generated by Django 3.2.21 on 2023-10-30 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0006_auto_20231030_1919'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poitem',
            name='mr_number',
        ),
    ]
