# Generated by Django 3.2.21 on 2023-11-13 18:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0009_mrnumber_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryitem',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ivitems', to='warehouse.unit', verbose_name='unit'),
        ),
    ]
