# Generated by Django 3.2.21 on 2023-11-16 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0011_materialissuerequest_miritem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='miritem',
            name='condition',
        ),
    ]
