# Generated by Django 3.2.21 on 2023-11-16 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0012_remove_miritem_condition'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryitem',
            name='mir_items',
            field=models.ManyToManyField(to='warehouse.MIRItem', verbose_name='MIR Items'),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='mrs_items',
            field=models.ManyToManyField(to='warehouse.MRSItem', verbose_name='MRS Items'),
        ),
    ]
