# Generated by Django 3.2.21 on 2023-11-16 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0013_auto_20231116_1322'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='miritem',
            name='pl_item',
        ),
    ]
