# Generated by Django 3.2.21 on 2023-11-16 16:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0015_miritem_mrs_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='materialissuerequest',
            name='mrs',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='mir', to='warehouse.materialreceiptsheet', verbose_name='MRS Num.'),
            preserve_default=False,
        ),
    ]
