# Generated by Django 3.2.21 on 2023-11-23 11:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0016_materialissuerequest_mrs'),
    ]

    operations = [
        migrations.AddField(
            model_name='mrsitem',
            name='warehouse',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='mrsitems', to='warehouse.warehouse', verbose_name='Warehouse'),
            preserve_default=False,
        ),
    ]
