# Generated by Django 3.2.21 on 2023-11-24 11:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0018_auto_20231124_1338'),
    ]

    operations = [
        migrations.AddField(
            model_name='materialissuerequest',
            name='dest_warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mirs_dest', to='warehouse.warehouse', verbose_name='Destination(To)'),
        ),
    ]
