# Generated by Django 3.2.21 on 2023-11-24 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0019_materialissuerequest_dest_warehouse'),
    ]

    operations = [
        migrations.AddField(
            model_name='materialissuerequest',
            name='transfer',
            field=models.BooleanField(default=False, verbose_name='Transfered'),
        ),
    ]
